# Kustomization for monitoring stack (Prometheus + Grafana + Loki)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus.yaml
  - grafana.yaml
  - loki.yaml
  - promtail.yaml
  - jaeger.yaml

configMapGenerator:
  - name: grafana-dashboard-uitgo-services
    files:
      - dashboards/uitgo-services.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-uitgo-alerts
    files:
      - dashboards/uitgo-alerts.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-uitgo-slo
    files:
      - dashboards/uitgo-slo.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-uitgo-overview
    files:
      - dashboards/uitgo-overview.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-uitgo-slo-sli
    files:
      - dashboards/uitgo-slo-sli.json
    options:
      labels:
        grafana_dashboard: "1"

commonLabels:
  app.kubernetes.io/part-of: uitgo-monitoring
