name: rider_app
description: UIT-Go Rider Flutter app
publish_to: "none"
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.0
  go_router: ^14.2.0
  shared_preferences: ^2.2.2  # Lưu trữ local
  http: ^1.1.0 
  dio: ^5.4.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.0              # API calls (optional, để sau này)
  web_socket_channel: ^2.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Welcome.json
