name: core_realtime
description: Realtime (WebSocket/MQTT) client.
version: 0.0.1
publish_to: "none"
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  web_socket_channel: ^2.4.0
dev_dependencies:
  lints: ^3.0.0
