global:
  scrape_interval: 15s

scrape_configs:
  - job_name: user-service
    static_configs:
      - targets:
          - user-service:8081

  - job_name: trip-service
    static_configs:
      - targets:
          - trip-service:8082

  - job_name: driver-service
    static_configs:
      - targets:
          - driver-service:8083
