name: driver_app
description: UIT-Go Driver Flutter app
publish_to: "none"
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"
dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ../../packages/design_system
  dio: ^5.5.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^8.0.0
  web_socket_channel: ^2.4.0
  intl: ^0.19.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
